circle: try using circleci's parallel test execution

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -879,6 +879,53 @@ jobs:
             export CIRCLE_PULL_REQUEST=none
             yarn klank
 
+  dev_parallel_browser_tests_using_circleci:
+    docker:
+      - image: circleci/python:3.8.0-node-browsers
+    working_directory: ~/directory-tests
+    parallelism: 4
+    environment:
+      TEST_ENV: "dev"
+      BROWSER: "chrome"
+      AUTO_RETRY: "false"
+    steps:
+      - checkout
+      - run:
+          name: Install JRE as it is required by Allure to generate an HTML report
+          command: |
+            PYTHONPATH=. behave \
+              --dry-run \
+              --no-source \
+              --no-summary \
+              --no-snippets \
+              --tags=~@wip \
+              --tags=~@fixme \
+              --tags=~@skip \
+              --format=mini \
+              features/domestic/header_footer.feature \
+              | grep -v "Supplied path\|Trying base directory" > scenario_titles.txt
+
+            cat scenario_titles.txt \
+              | circleci tests split > /tmp/tests-to-run
+
+            cat /tmp/tests-to-run | while IFS=$'\r' read -r title ; do
+              echo "Added task for scenario: '${title}'"
+              PYTHONPATH=. behave features/ \
+              --format=allure_behave.formatter:AllureFormatter \
+              --outfile={browser}_results/ \
+              --format=pretty \
+              --no-skipped \
+              --tags=~@wip \
+              --tags=~@fixme \
+              --tags=~@skip \
+              --tags=~@stage-only \
+              --name "${title}" && {
+                echo "Pass: ${title}"
+              } || {
+                echo "Failed: ${title}"
+              }
+            done
+
 workflows:
   version: 2
 
@@ -1206,4 +1253,4 @@ workflows:
 
   run_browser_tests_in_parallel_in_dev:
     jobs:
-      - dev_parallel_browser_tests
+      - dev_parallel_browser_tests_using_circleci
